const settings = {
    defaultNumberOfBoids: 25,
    minNumberOfBoids: 1,
    maxNumberOfBoids: 50,
    defaultVisualRange: 100,
    minVisualRange: 1,
    maxVisualRange: 200,
    defaultSpeedLimit: 50,
    minSpeedLimit: 1,
    maxSpeedLimit: 100,
    defaultCohesion: 75,
    minCohesion: 1,
    maxCohesion: 150,
    defaultSeparation: 10,
    minSeparation: 1,
    maxSeparation: 20,
    defaultAlignment: 10,
    minAlignment: 1,
    maxAlignment: 20,
}
export default settings